language: cpp

jobs:
  include:

    - name: "Bionic.18.04"
      dist: bionic
      os: linux
      env: BUILD_FLAG=-d

    - name: "Focal.20.04"
      dist: focal
      os: linux
      env: BUILD_FLAG=-d

    #- name: "Android"
      #dist: focal
      #os: linux
      #env: BUILD_FLAG=-a

before_install:
    - if [[ "$BUILD_FLAG" == "-a" ]]; then
        sudo apt-get install -y openjdk-8-jre
      else
        sudo apt-get update;
        sudo apt-get install -y --no-install-recommends qtbase5-dev qttools5-dev-tools devscripts fakeroot debhelper ;
      fi;
      #- sh: sudo apt-get install -y --no-install-recommends git-build-recipe dh-make git-buildpackage;
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update ;
        brew install qt5 ;
        export PATH=$(brew --prefix)/opt/qt5/bin:$PATH ;
        echo $PATH;
      fi


script:
-   chmod +x build.sh;
    ./build.sh ${BUILD_FLAG} true;
