language: cpp

matrix:
  include:
    #- name: "Xenial 16.04 amd64"
    #  dist: xenial
#    - name: "Bionic 18.04 amd64"
#      dist: bionic
    - name: "Focal 20.04 amd64"
      dist: focal
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test

before_install:
#- sudo apt-get -y install gcc-9  g++-9
#- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
#- sudo update-alternatives --config gcc
- sudo apt-get -y install qt5-qmake qtbase5-dev qttools5-dev-tools

script:
  #- gcc -v
  #- g++ -v
  - qmake -qt=qt5
  - make -j4
