 
version: 0.0.{build}

environment:
  matrix:
  
  - QTDIR: C:\Qt\5.15.2\msvc2019_64
    BUILD_PLATFORMID: "x64"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    WINVER: Win10
    
  - QTDIR: C:\Qt\5.15.2\msvc2019
    BUILD_PLATFORMID: "x86"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    WINVER: Win10
    
  - QTDIR: C:\Qt\5.13.2\msvc2015_64
    BUILD_PLATFORMID: "x64"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    WINVER: Win8

build_script:
  - build.cmd

artifacts:
  - path: '*.zip'
    name: 'logview.%BUILD_PLATFORMID%.%APPVEYOR_BUILD_VERSION%'

deploy:
- provider: GitHub
  description: 'New release of logview'
  auth_token:
    secure: Wzt04IzSwnytdau8R6dpRXet/npbyur3S02EA35OQBGRKFZyJuUjh95OLFzDrX3N
  on:
   appveyor_repo_tag: true
