name: qt5_android
on: 
  push:
  
jobs:
  build:
    name: Run build
    runs-on: ubuntu-20.04
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.2
        with:
          version: 5.15.2
          target: android
      - name: checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: build android
        run: |
          ls -l /usr/lib/jvm/;
          export ANDROID_SDK_ROOT=$ANDROID_HOME;
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle;
          export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64;
          chmod +x build.sh;
          ./build.sh -a true;
