name: qt5_android
on: [push, pull_request]
  
jobs:
  build:
    name: Run build
    runs-on: ubuntu-20.04
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.2
        with:
          version: 5.15.2
          target: android
      - name: checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build android version
        run: |
          echo "ls -l /usr/lib/jvm/";
          ls -l /usr/lib/jvm/;
          echo "ls -l /usr/local/lib/android/sdk";
          ls -l /usr/local/lib/android/sdk;
          echo "ls -l /usr/local/lib/android/sdk/ndk";
          ls -l /usr/local/lib/android/sdk/ndk;
          echo "github.event_name [${{github.event_name}}]";
          echo "github.ref        [${{github.ref}}]";
          echo "github.event.release.upload_url [${{ github.event.release.upload_url }}]";
          export ANDROID_SDK_ROOT=$ANDROID_HOME;
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle;
          export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64;
          chmod +x build.sh;
          ./build.sh -a true;
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          retention-days: 1
          path: |
                logview_android*.aab
                logview_android*.apk
      - name: Upload release AAB
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./logview_android*.aab
          asset_name: aab
          asset_content_type: application/octet-stream
      - name: Upload release APK
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./logview_android*.apk
          asset_name: apk
          asset_content_type: application/octet-stream
