name: qt5_android
on: [push, pull_request]
  
jobs:
  build:
    name: Run build
    runs-on: ubuntu-20.04
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.2
        with:
          version: 5.15.2
          target: android
      - name: checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build android version
        run: |
          ls -l /usr/lib/jvm/;
          ls -l /usr/local/lib/android/sdk
          ls -l /usr/local/lib/android/sdk/ndk
          echo "github.event_name [${{github.event_name}}]"
          echo "github.ref        [${{github.ref}}]"
          export ANDROID_SDK_ROOT=$ANDROID_HOME;
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle;
          export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64;
          chmod +x build.sh;
          ./build.sh -a true;
          echo "BUILD_VERSION_IDS=[$BUILD_VERSION_IDS]"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact_$BUILD_VERSION_IDS
          retention-days: 1
          path: |
                logview_android*.aab
                logview_android*.apk
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: startsWith(github.ref, 'refs/tags/v')
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload release AAB
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./logview_android*.aab
          asset_name: aab
          asset_content_type: application/octet-stream
      - name: Upload release APK
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./logview_android*.apk
          asset_name: apk
          asset_content_type: application/octet-stream
